version: '3.7'

services:
  standalone:
    image: apachepulsar/pulsar:2.7.0
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address 127.0.0.1"
      
